[build]
builder = "dockerfile"
dockerfilePath = "./Assembly.Horizon.WebApi/Dockerfile"

[deploy]
startCommand = "dotnet ./Assembly.Horizon.WebApi.dll"
restartPolicyType = "always"
healthcheckPath = "/swagger/index.html"
healthcheckTimeout = 300

[http]
port = 7220